import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../language_provider.dart';

class AppLocalizations {
  final String locale;

  AppLocalizations(this.locale);

  // Helper method to get localizations from context
  static AppLocalizations of(BuildContext context) {
    final languageProvider = Provider.of<LanguageProvider>(
      context,
      listen: false,
    );
    return AppLocalizations(languageProvider.currentLanguage);
  }

  // Add translations for common UI elements
  static final Map<String, Map<String, String>> _localizedValues = {
    'English': {
      // Transaction ID dialog
      'confirmYourPayment': 'Confirm Your Payment',
      'iUnderstand': 'I Understand',
      'submit': 'Submit',
      'accept': 'Accept',
      'decline': 'Decline',
      'openSettings': 'Open Settings',
      'conversationStorageConsentTitle': 'Save Conversation History?',
      'conversationStorageConsentMessage': 'Would you like to save your conversation history? This helps provide better support but stores your messages securely. You can change this later in settings.',
      'phoneCallNotSupportedOnWeb': 'Phone calls are not supported on web. Please use a mobile device.',
      'smsNotSupportedOnWeb': 'SMS is not supported on web. Please use a mobile device.',
      'pleaseEnterTheFinancialTransactionId':
          'Please enter the Financial Transaction ID from your MTN payment confirmation message',
      'pleaseWaitForOurTeamToConfirmYourTransaction':
          'Please wait for our team to confirm your transaction. This usually takes less than 10 minutes during business hours.',
      'confirmAndSubmit': 'Confirm & Submit',
      'transactionIdSubmittedSuccessfully':
          'Transaction ID submitted successfully. Our team will verify and activate your account shortly.',
      'pleaseEnterTransactionId': 'Please enter a valid Transaction ID',

      // Settings
      'settings': 'Settings',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'cancel': 'Cancel',
      'searchSettings': 'Search Settings',
      'selectFontFamily': 'Select Font Family',
      'selectFontSize': 'Select Font Size',
      'languageAudio': 'Language Audio',
      'dataPerformance': 'Data Performance',
      'dailyAffirmations': 'Daily Affirmations',
      'chooseLanguageDescription': 'Choose your preferred language',
      'chooseFontFamilyDescription':
          'Choose a font that feels comfortable to read',
      'fontSizeFollowsSystem':
          'Font size follows your device accessibility setting.',
      'database': 'Database',
      'contentPolicyReporting': 'Content Policy Reporting',
      'adminControls': 'Admin Controls',
      'lowDataMode': 'Low Data Mode',
      'imageLazyLoading': 'Image Lazy Loading',
      'offlineMode': 'Offline Mode',

      // Navigation
      'home': 'Home',
      'forum': 'Forum',
      'mahoro': 'Mahoro',
      'muganga': 'Muganga',

      // Accessibility
      'accessibility': 'Accessibility',
      'fontFamily': 'Font Family',
      'fontSize': 'Font Size',
      'highContrastMode': 'High Contrast Mode',
      'reduceMotion': 'Reduce Motion',
      'textToSpeech': 'Text-to-Speech',
      'voiceToText': 'Voice-to-Text',

      // Appearance
      'appearance': 'Appearance',

      // Notifications
      'notifications': 'Notifications',
      'forumReplies': 'Forum Replies',
      'weeklyCheckIns': 'Weekly Check-Ins',
      'systemUpdates': 'System Updates',

      // Privacy & Security
      'privacySecurity': 'Privacy Policy',
      'emergencyContacts': 'Emergency Contacts',
      'logout': 'Logout',
      'signIn': 'Sign In',
      'editProfile': 'Edit Profile',

      // Forum
      'safeSpaceToShare': 'Safe space to share',
      'noPostsYet': 'No posts yet',
      'beTheFirstToStartConversation': 'Be the first to start a conversation',
      'createPost': 'Create Post',
      'joinTheConvo': 'Join The Convo',
      'search': 'Search',
      'searchPosts': 'Search posts...',
      'searchPostsLabel': 'Search Posts',
      'searchLabel': 'Search...',
      'likes': 'Likes',
      'replies': 'Replies',
      'reply': 'Reply',
      'anonymous': 'Anonymous',
      'postTitle': 'Post Title',
      'postContent': 'Post Content',
      'post': 'Post',

      // Mahoro
      'yourSupportCompanion': 'Your 24/7 support companion',
      'typeMessage': 'Type a message...',
      'send': 'Send',

      // Muganga
      'mugangaTherapy': 'Muganga Therapy',
      'professionalMentalHealthSupport': 'Professional mental health support',
      'monthlySubscription': 'Monthly Subscription',
      '2000RWF': '2,000 RWF',
      'unlimitedTherapySessionsWithCertifiedProfessionals':
          'Unlimited therapy sessions with certified professionals',
      'subscribeNow': 'Subscribe Now',
      'mtnMobileMoneyPayment': 'MTN Mobile Money Payment',
      'payWithMtnMobileMoney': 'Pay with MTN Mobile Money',
      'dialTheFollowingUssdCodeOnYourMtnPhone':
          'Dial the following USSD code on your MTN phone:',
      'ussdCode': '*182*1*1*0780332779*2000#',
      'afterPaymentYouWillReceive': 'After payment, you will receive:',
      'immediateConfirmationMessage': 'Immediate confirmation message',
      'paymentReceiptFromOurTeam': 'Payment receipt from our team',
      'accessToTherapyBooking': 'Access to therapy booking',
      'note': 'Note:',
      'paymentGoesDirectlyToOurTeamAt250780332779TheNumberIsRegisteredToAlineIRADUKUNDAOurChiefOperationsOfficerSheWillBeContactingYouAsSoonAsThePaymentIsReceivedForAccountActivation':
          'Payment goes directly to our team at +250780332779. The number is registered to Aline IRADUKUNDA, our Chief Operations Officer. She will be contacting you as soon as the payment is received for account activation.',
      'iveMadeThePayment': 'I\'ve Made the Payment',
      'payEasilyWithMtnMobileMoneyAndGetInstantAccessToProfessionalTherapy':
          'Pay easily with MTN Mobile Money and get instant access to professional therapy',
      'certifiedTherapists': 'Certified Therapists',
      'licensedMentalHealthProfessionals':
          'Licensed mental health professionals',
      'flexibleScheduling': 'Flexible Scheduling',
      'bookSessionsAtYourConvenience': 'Book sessions at your convenience',
      'oneOnOneSessions': '1-on-1 Sessions',
      'privateConfidentialTherapySessions':
          'Private, confidential therapy sessions',

      // Home
      'welcomeBack': 'Welcome back,',
      'yourSafeSpaceForHealing': 'Your safe space for healing',
      'emergencyHelp': 'SOS - Emergency Help',
      'getImmediateSupport': 'Get immediate support',
      'emergencyCall': 'Emergency Call',
      'wouldYouLikeToCallEmergencyServicesNow':
          'Would you like to call emergency services now?',
      'callNow': 'Call Now',
      'exploreServices': 'Explore Services',
      'recentPosts': 'Recent Posts',
      'viewAll': 'View All',
      'quickActions': 'Quick Actions',
      'howAreYouToday': 'How are you today?',

      // Home - Mood tracking
      'howAreYouFeelingToday': 'How are you feeling today?',
      'great': 'Great',
      'good': 'Good',
      'okay': 'Okay',
      'sad': 'Sad',
      'bad': 'Bad',

      // Home - Resources
      'resources': 'Resources',
      'selfCareTips': 'Self-Care Tips',
      'dailyWellnessPractices': 'Daily wellness practices',
      'safetyPlanning': 'Safety Planning',
      'personalSafetyResources': 'Personal safety resources',
      'crisisSupport': 'Crisis Support',
      'helplineNumbers': '24/7 helpline numbers',
      'educationalContent': 'Educational Content',
      'learnAboutHealing': 'Learn about healing',

      // App Name & Branding
      'hopeCoreHub': 'HopeCore Hub',
      'ignitingHope': 'Igniting Hope',

      // SOS/Emergency Section
      'sos': 'SOS',
      'youAreNotAlone': 'You Are Not Alone',
      'everythingIsGoingToBeOkay': 'Everything is going to be okay. 💜',
      'ifYoureInImmediateDanger': 'If you\'re in immediate danger, we\'re here to help connect you with the right support.',
      'youAreBraveForReachingOut': 'You are brave for reaching out.',
      'howWouldYouLikeToGetHelp': 'How would you like to get help?',
      'call': 'Call',
      'message': 'Message',
      'chooseEmergencyContact': 'Choose Emergency Contact',
      'selectWhoYoudLikeToCall': 'Select who you\'d like to call for immediate assistance:',
      'isangeOneStopCenter': 'Isange One Stop Center',
      'genderBasedViolenceSupport': 'Gender-based violence support',
      'rwandaInvestigationBureau': 'Rwanda Investigation Bureau (RIB)',
      'criminalInvestigationsSafety': 'Criminal investigations & safety',
      'hopeCoreHubTeam': 'HopeCore Hub Team',
      'wellHelpContactAuthorities': 'We\'ll help contact authorities',
      'back': 'Back',
      'makeAPhoneCall': 'Make a Phone Call',
      'sendATextMessage': 'Send a Text Message',
      'sendAMessage': 'Send a Message',
      'selectWhoYoudLikeToMessage': 'Select who you\'d like to message for support:',
      'trustedContact': 'Trusted Contact',
      'addFromPhonebook': 'Add from phonebook',
      'whatsappHopeCoreHubTeam': 'WhatsApp HopeCore Hub Team',
      'helloINeedHelpRegardingSafetyConcern': 'Hello, I need help regarding safety concern.',
      'addTrustedContact': 'Add Trusted Contact',
      'contactName': 'Contact Name',
      'phoneNumber': 'Phone Number',
      'pleaseEnterAValidPhoneNumber': 'Please enter a valid phone number',
      'couldNotLaunchPhoneCall': 'Could not launch phone call to [number]',
      'errorMakingPhoneCall': 'Unable to make phone call. If you\'re in immediate danger, please call emergency services (112) directly.',
      'couldNotLaunchSms': 'Could not launch SMS to [number]',
      'errorSendingSms': 'Unable to send SMS. If you need immediate help, please call emergency services (112) or use the SOS button.',
      'couldNotLaunchWhatsapp': 'Could not launch WhatsApp. Please make sure WhatsApp is installed.',
      'errorSendingWhatsappMessage': 'Error sending WhatsApp message: [error]',
      'contactsPermissionRequired': 'Contacts permission is required to pick from phonebook.',
      'pleaseEnableContactsPermission': 'Please enable contacts permission in app settings.',
      'errorAccessingContacts': 'Error accessing contacts: [error]',
      'hiINeedToTalk': 'Hi, I need to talk. Could you please call me when you have a moment?',

      // Quick Access Section
      'quickAccess': 'Quick Access',
      'connectWithCommunity': 'Connect with community',
      'aiSupportCompanion': 'AI Support Companion',
      'professionalSupport': 'Professional Support',
      'customizeYourExperience': 'Customize your experience',

      // Mood Tracking Section
      'howCanWeSupportYouToday': 'How can we support you today?',
      'itsGreatToSeeYoureFeelingGood': 'It\'s great to see you\'re feeling good! Would you like to share your positive experiences or learn ways to maintain this mood?',
      'sometimesWeAllFeelNeutral': 'Sometimes we all feel a bit neutral. Would you like to talk about what\'s on your mind or explore ways to boost your mood?',
      'imSorryYoureFeelingDown': 'I\'m sorry you\'re feeling down. Remember that it\'s okay to not be okay, and talking about it can help. Would you like some support?',
      'iCanSeeYoureHavingDifficultTime': 'I can see you\'re having a difficult time. Please remember you\'re not alone, and there are resources available to help you through this.',
      'thankYouForSharingHowYoureFeeling': 'Thank you for sharing how you\'re feeling. Would you like to talk more about it?',
      'talkToMahoro': 'Talk to Mahoro',
      'joinForum': 'Join Forum',

      // Emergency Contacts Footer
      'isangeOneStopCenterLabel': 'Isange One Stop Center:',
      'rwandaInvestigationBureauLabel': 'Rwanda Investigation Bureau (RIB):',
      'hopeCoreTeamLabel': 'HopeCore Team:',
      'helpIsAvailable247': 'Help is available 24/7',

      // Daily Affirmation Section
      'dailyAffirmation': 'Daily Affirmation',
      'dailyAffirmationQuote': 'You are stronger than you know, braver than you feel, and more loved than you imagine.',

      // Guest Mode Messages
      'guestMode': 'Guest Mode',
      'youreCurrentlyUsingAppAsGuest': 'You\'re currently using the app as a guest. Sign in or create an account to access all features and save your progress.',
      'loginRegister': 'Login / Register',
      'continueAsGuest': 'Continue as Guest',
      'logInToAccessAllFeatures': 'Log in to access all features',
      'refreshingLoginStatus': 'Refreshing login status...',

      // Forum Screen
      'yourSafeSpaceToHeal': 'Your Safe Space to Heal',
      'thisIsASafeModeratedSpace': 'This is a safe, moderated space. All posts are anonymous and supportive.',
      'postingAs': 'Posting as',
      'youArePostingAsGuest': 'You are posting as a guest. Sign in to track your posts.',
      'title': 'Title',
      'shareYourThoughts': 'Share your thoughts, experiences, or ask for support...',
      'share': 'Share',
      'edit': 'Edit',
      'delete': 'Delete',
      'remove': 'Remove',
      'flagReport': 'Flag/Report',
      'deletePost': 'Delete Post',
      'areYouSureYouWantToDelete': 'Are you sure you want to delete this post? This action cannot be undone.',
      'postDeletedSuccessfully': 'Post deleted successfully',
      'errorDeletingPost': 'Error deleting post: [error]',
      'editPost': 'Edit Post',
      'editYourMessage': 'Edit your message...',
      'save': 'Save',
      'update': 'Update',
      'postUpdatedSuccessfully': 'Post updated successfully',
      'errorUpdatingPost': 'Error updating post: [error]',
      'replySentSuccessfully': 'Reply sent successfully',
      'errorSendingReply': 'Error sending reply: [error]',
      'typeAReply': 'Type a reply...',
      'youHaveAlreadyLikedThisPost': 'You have already liked this post',
      'errorLikingPost': 'Error liking post: [error]',
      'pleaseLogInToReply': 'Please log in to reply',
      'pleaseLogInToLikePosts': 'Please log in to like posts',
      'pleaseLogInToReportContent': 'Please log in to report content',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'jan': 'Jan',
      'feb': 'Feb',
      'mar': 'Mar',
      'apr': 'Apr',
      'may': 'May',
      'jun': 'Jun',
      'jul': 'Jul',
      'aug': 'Aug',
      'sep': 'Sep',
      'oct': 'Oct',
      'nov': 'Nov',
      'dec': 'Dec',
      'areYouSureYouWantToLogout': 'Are you sure you want to logout?',
      'welcome': 'Welcome,',
      'youAreBrowsingAsGuest': 'You are browsing as a guest',
      'loggedInAs': 'Logged in as',
      'errorLoadingPostsUsingFallback': 'Error loading posts. Using fallback content.',
      'errorCreatingPost': 'Error creating post: [error]',
      'errorLoadingPosts': 'Error loading posts: [error]',
      'errorLoadingPostsTitle': 'Unable to Load Posts',
      'errorLoadingPostsRetry': 'Failed to load posts. Please check your connection and try again.',
      'retry': 'Retry',
      'ifInImmediateDanger': 'If you\'re in immediate danger, call emergency services',
      'ifInImmediateDangerCallEmergency': 'If you\'re in immediate danger, please call emergency services (112) or use the SOS button for help.',
      'createAPost': 'Create a Post',
      'postingAsUsername': 'Posting as [username]',

      // Mahoro AI Screen
      'aiSupportActive': 'AI Support Active',
      'apiConnectionError': 'API Connection Error',
      'english': 'English',
      'kinyarwanda': 'Kinyarwanda',
      'francais': 'Français',
      'swahili': 'Swahili',
      'murahoImMahoro': 'Muraho! I\'m Mahoro, your supportive AI companion. How can I help you today? You can speak to me in Kinyarwanda, English, Swahili, or French.',
      'apiKeyNotFound': 'API key not found. Please contact support.',
      'apiKeyRemoved': 'API key removed. Mahoro will prompt for a new key.',
      'pleaseEnterValidApiKey': 'Please enter a valid API key',
      'invalidApiKeyFormat': 'Invalid API key format. Claude keys start with "sk-ant-"',
      'apiKeySaved': 'API key saved. Mahoro is ready to use.',
      'apiKeyUpdatedSuccessfully': 'API key updated successfully. Mahoro is ready to use.',
      'claudeApiKey': 'Claude API Key',
      'claudeApiKeyRequired': 'Claude API Key Required',
      'enterApiKey': 'Enter API Key',
      'mahoroNeedsValidApiKey': 'Mahoro needs a valid Claude API key to connect. Enter a key below to continue.',
      'updateClaudeApiKeyDescription': 'Update the Claude API key for Mahoro AI. The key is stored securely on this device.',
      'enterClaudeApiKeyDescription': 'Enter a Claude API key to enable Mahoro AI. The key will be stored securely on this device.',
      'apiKeyLabel': 'API Key',
      'updatingKeyWillAffectAllUsers': 'Updating the key will affect all users on this device.',
      'imHavingTroubleWithAuthentication': 'I\'m having trouble with authentication. Please contact support.',
      'imHavingTroubleConnecting': 'I\'m having trouble connecting right now. Please try again later.',
      'imSorryIEncounteredAnError': 'I\'m sorry, I encountered an error. Please try again.',
      'tooManyRequestsPleaseWait': 'I\'m receiving too many requests. Please wait a moment and try again.',
      'policeEmergency': 'Police Emergency',
      'report': 'Report',
      'thankYouForReportingContent': 'Thank you for reporting this content. We will review it promptly.',
      'your247SupportCompanion': 'Your 24/7 support companion',

      // Muganga Therapy Screen
      'comingSoon': 'Coming Soon',
      'mugangaTherapyCurrentlyInDevelopment': 'Muganga Therapy is currently in development and will launch soon.',
      'weAreBuildingMostAffordable': 'We are building the most affordable GenZ-friendly Mental Health Support in Rwanda.',
      'stayTunedForUpdates': 'Stay tuned for updates!',
      'loadingSubscriptionData': 'Loading subscription data...',
      'errorLoadingSubscriptionData': 'Error loading subscription data',
      'retry': 'Retry',

      // Settings Screen - Additional
      'reduceDataUsageForRemoteAreas': 'Reduce data usage for remote areas',
      'loadImagesOnlyWhenNeeded': 'Load images only when needed',
      'cacheContentForOfflineAccess': 'Cache content for offline access',
      'useDarkThemeThroughoutApp': 'Use dark theme throughout the app',
      'forumPosts': 'Forum Posts',
      'newMessagesInForum': 'New messages in the forum',
      'forumRepliesLabel': 'Forum replies',
      'appUpdatesAndNews': 'App updates and news',
      'guestUser': 'Guest User',
      'online': 'Online',
      'pageComingSoon': 'page coming soon',
      'pageIsNotYetImplemented': 'page is not yet implemented',
      'dataPerformanceLabel': 'Data Performance',
      'appearanceLabel': 'Appearance',
      'accessibilityLabel': 'Accessibility',
      'notificationsLabel': 'Notifications',
      'emergencyContactsLabel': 'Emergency Contacts',
      'selectFontFamilyLabel': 'Select Font Family',
      'selectFontSizeLabel': 'Select Font Size',
      'fontSizeFollowsDevice': 'Font size follows your device accessibility setting.',
      'highContrastModeLabel': 'High Contrast Mode',
      'reduceMotionLabel': 'Reduce Motion',
      'textToSpeechLabel': 'Text-to-Speech',
      'voiceToTextLabel': 'Voice-to-Text',
      'darkModeLabel': 'Dark Mode',
      'lowDataModeLabel': 'Low Data Mode',
      'imageLazyLoadingLabel': 'Image Lazy Loading',
      'offlineModeLabel': 'Offline Mode',

      // Content Reporting Dialog
      'reportContent': 'Report Content',
      'whyAreYouReportingThisContent': 'Why are you reporting this content?',
      'inappropriateContent': 'Inappropriate Content',
      'contentThatViolatesCommunityGuidelines': 'Content that violates community guidelines',
      'harmfulOrDangerous': 'Harmful or Dangerous',
      'contentThatCouldCauseHarm': 'Content that could cause harm to users',
      'spam': 'Spam',
      'unwantedOrRepetitiveContent': 'Unwanted or repetitive content',
      'misinformation': 'Misinformation',
      'falseOrMisleadingInformation': 'False or misleading information',
      'harassmentOrBullying': 'Harassment or Bullying',
      'contentThatTargetsOrBullies': 'Content that targets or bullies users',
      'other': 'Other',
      'otherConcernsNotListed': 'Other concerns not listed above',
      'pleaseSpecify': 'Please specify',
      'additionalDetailsOptional': 'Additional details (optional)',
      'provideAnyAdditionalContext': 'Provide any additional context...',
      'submitReport': 'Submit Report',
      'loading': 'Loading...',
      'alreadyReported': 'Already Reported',
      'youHaveAlreadyReportedThisContent': 'You have already reported this content. Our moderation team will review it and take appropriate action.',
      'ok': 'OK',
      'reportSubmittedSuccessfully': 'Report submitted successfully. Thank you for helping keep our community safe.',
      'failedToSubmitReport': 'Failed to submit report. Please try again.',
      'anErrorOccurred': 'An error occurred. Please try again.',
      'pleaseSelectReasonForReporting': 'Please select a reason for reporting this content.',
      'pleaseProvideCustomReason': 'Please provide a custom reason.',
      'aiMessage': 'AI Message',
      'forumPost': 'Forum Post',
      'forumReply': 'Forum Reply',
      'otherContent': 'Other Content',

      // Error & Success Messages
      'close': 'Close',
      'pickFromPhonebook': 'Pick from Phonebook',
      'selectContact': 'Select Contact',
    },
    'French': {
      // Transaction ID dialog
      'confirmYourPayment': 'Confirmez Votre Paiement',
      'iUnderstand': 'Je Comprends',
      'submit': 'Soumettre',
      'pleaseEnterTheFinancialTransactionId':
          'Veuillez saisir l\'ID de transaction financière de votre message de confirmation de paiement MTN',
      'pleaseWaitForOurTeamToConfirmYourTransaction':
          'Veuillez patienter pendant que notre équipe confirme votre transaction. Cela prend généralement moins de 10 minutes pendant les heures de bureau.',
      'confirmAndSubmit': 'Confirmer et Soumettre',
      'transactionIdSubmittedSuccessfully':
          'ID de transaction soumis avec succès. Notre équipe vérifiera et activera votre compte sous peu.',
      'pleaseEnterTransactionId': 'Veuillez saisir un ID de transaction valide',

      // Settings
      'settings': 'Paramètres',
      'darkMode': 'Mode Sombre',
      'language': 'Langue',
      'selectLanguage': 'Choisir la Langue',
      'cancel': 'Annuler',
      'searchSettings': 'Rechercher dans les Paramètres',
      'selectFontFamily': 'Sélectionner la Police',
      'selectFontSize': 'Sélectionner la Taille de Police',
      'languageAudio': 'Langue & Audio',
      'chooseLanguageDescription': 'Choisissez votre langue préférée',
      'chooseFontFamilyDescription': 'Choisissez une police confortable à lire',
      'fontSizeFollowsSystem':
          'La taille du texte suit les réglages d\'accessibilité de votre appareil.',
      'database': 'Base de Données',
      'contentPolicyReporting': 'Politique de Contenu & Signalement',
      'adminControls': 'Contrôles Administrateur',
      'lowDataMode': 'Mode Données Réduites',
      'imageLazyLoading': 'Chargement Différé des Images',
      'offlineMode': 'Mode Hors Ligne',

      // Navigation
      'home': 'Accueil',
      'forum': 'Forum',
      'mahoro': 'Mahoro',
      'muganga': 'Muganga',

      // Accessibility
      'accessibility': 'Accessibilité',
      'fontFamily': 'Police d\'écriture',
      'fontSize': 'Taille de Police',
      'highContrastMode': 'Mode Contraste Élevé',
      'reduceMotion': 'Réduire les Animations',
      'textToSpeech': 'Synthèse Vocale',
      'voiceToText': 'Reconnaissance Vocale',

      // Appearance
      'appearance': 'Apparence',

      // Notifications
      'notifications': 'Notifications',
      'forumReplies': 'Réponses du Forum',
      'weeklyCheckIns': 'Vérifications Hebdomadaires',
      'systemUpdates': 'Mises à Jour Système',

      // Privacy & Security
      'privacySecurity': 'Confidentialité & Sécurité',
      'emergencyContacts': 'Contacts d\'Urgence',
      'logout': 'Déconnexion',
      'signIn': 'Connexion',
      'editProfile': 'Modifier le Profil',

      // Forum
      'safeSpaceToShare': 'Espace sûr pour partager',
      'noPostsYet': 'Pas encore de publications',
      'beTheFirstToStartConversation':
          'Soyez le premier à démarrer une conversation',
      'createPost': 'Créer une Publication',
      'joinTheConvo': 'Rejoindre la Conversation',
      'search': 'Rechercher',
      'searchPosts': 'Rechercher des publications...',
      'searchPostsLabel': 'Rechercher des Publications',
      'searchLabel': 'Rechercher...',
      'likes': 'J\'aime',
      'replies': 'Réponses',
      'reply': 'Répondre',
      'anonymous': 'Anonyme',
      'postTitle': 'Titre de la Publication',
      'postContent': 'Contenu de la Publication',
      'post': 'Publier',

      // Mahoro
      'yourSupportCompanion': 'Votre compagnon de soutien 24/7',
      'typeMessage': 'Tapez un message...',
      'send': 'Envoyer',

      // Muganga
      'mugangaTherapy': 'Thérapie Muganga',
      'professionalMentalHealthSupport':
          'Soutien professionnel en santé mentale',
      'monthlySubscription': 'Abonnement Mensuel',
      '2000RWF': '2 000 RWF',
      'unlimitedTherapySessionsWithCertifiedProfessionals':
          'Sessions de thérapie illimitées avec des professionnels certifiés',
      'subscribeNow': 'S\'abonner Maintenant',
      'mtnMobileMoneyPayment': 'Paiement par MTN Mobile Money',
      'payWithMtnMobileMoney': 'Payez avec MTN Mobile Money',
      'dialTheFollowingUssdCodeOnYourMtnPhone':
          'Composez le code USSD suivant sur votre téléphone MTN:',
      'ussdCode': '*182*1*1*0780332779*2000#',
      'afterPaymentYouWillReceive': 'Après le paiement, vous recevrez:',
      'immediateConfirmationMessage': 'Message de confirmation immédiat',
      'paymentReceiptFromOurTeam': 'Reçu de paiement de notre équipe',
      'accessToTherapyBooking': 'Accès à la réservation de thérapie',
      'note': 'Note:',
      'paymentGoesDirectlyToOurTeamAt250780332779TheNumberIsRegisteredToAlineIRADUKUNDAOurChiefOperationsOfficerSheWillBeContactingYouAsSoonAsThePaymentIsReceivedForAccountActivation':
          'Le paiement va directement à notre équipe au +250780332779. Le numéro est enregistré au nom d\'Aline IRADUKUNDA, notre directrice des opérations. Elle vous contactera dès que le paiement sera reçu pour l\'activation du compte.',
      'iveMadeThePayment': 'J\'ai Effectué le Paiement',
      'payEasilyWithMtnMobileMoneyAndGetInstantAccessToProfessionalTherapy':
          'Payez facilement avec MTN Mobile Money et obtenez un accès instantané à une thérapie professionnelle',
      'certifiedTherapists': 'Thérapeutes Certifiés',
      'licensedMentalHealthProfessionals':
          'Professionnels de la santé mentale agréés',
      'flexibleScheduling': 'Horaires Flexibles',
      'bookSessionsAtYourConvenience':
          'Réservez des séances à votre convenance',
      'oneOnOneSessions': 'Sessions Individuelles',
      'privateConfidentialTherapySessions':
          'Sessions de thérapie privées et confidentielles',

      // Home
      'welcomeBack': 'Bienvenue,',
      'yourSafeSpaceForHealing': 'Votre espace sécurisé pour guérir',
      'emergencyHelp': 'SOS - Aide d\'Urgence',
      'getImmediateSupport': 'Obtenir une aide immédiate',
      'emergencyCall': 'Appel d\'Urgence',
      'wouldYouLikeToCallEmergencyServicesNow':
          'Voulez-vous appeler les services d\'urgence maintenant?',
      'callNow': 'Appeler Maintenant',
      'exploreServices': 'Explorer les Services',
      'recentPosts': 'Publications Récentes',
      'viewAll': 'Voir Tout',
      'quickActions': 'Actions Rapides',
      'howAreYouToday': 'Comment allez-vous aujourd\'hui?',

      // Home - Mood tracking
      'howAreYouFeelingToday': 'Comment vous sentez-vous aujourd\'hui?',
      'great': 'Excellent',
      'good': 'Bien',
      'okay': 'Correct',
      'sad': 'Triste',
      'bad': 'Mal',

      // Home - Resources
      'resources': 'Ressources',
      'selfCareTips': 'Conseils d\'Auto-Soins',
      'dailyWellnessPractices': 'Pratiques quotidiennes de bien-être',
      'safetyPlanning': 'Planification de Sécurité',
      'personalSafetyResources': 'Ressources de sécurité personnelle',
      'crisisSupport': 'Soutien en Crise',
      'helplineNumbers': 'Numéros d\'assistance 24/7',
      'educationalContent': 'Contenu Éducatif',
      'learnAboutHealing': 'Apprendre sur la guérison',

      // App Name & Branding
      'hopeCoreHub': 'HopeCore Hub',
      'ignitingHope': 'Allumer l\'Espoir',

      // SOS/Emergency Section
      'sos': 'SOS',
      'youAreNotAlone': 'Vous N\'êtes Pas Seul',
      'everythingIsGoingToBeOkay': 'Tout va bien se passer. 💜',
      'ifYoureInImmediateDanger': 'Si vous êtes en danger immédiat, nous sommes là pour vous aider à contacter le bon soutien.',
      'youAreBraveForReachingOut': 'Vous êtes courageux de nous contacter.',
      'howWouldYouLikeToGetHelp': 'Comment souhaitez-vous obtenir de l\'aide?',
      'call': 'Appeler',
      'message': 'Message',
      'chooseEmergencyContact': 'Choisir un Contact d\'Urgence',
      'selectWhoYoudLikeToCall': 'Sélectionnez qui vous souhaitez appeler pour une assistance immédiate:',
      'isangeOneStopCenter': 'Isange One Stop Center',
      'genderBasedViolenceSupport': 'Soutien en cas de violence basée sur le genre',
      'rwandaInvestigationBureau': 'Bureau d\'Enquête du Rwanda (RIB)',
      'criminalInvestigationsSafety': 'Enquêtes criminelles et sécurité',
      'hopeCoreHubTeam': 'Équipe HopeCore Hub',
      'wellHelpContactAuthorities': 'Nous vous aiderons à contacter les autorités',
      'back': 'Retour',
      'makeAPhoneCall': 'Passer un Appel',
      'sendATextMessage': 'Envoyer un SMS',
      'sendAMessage': 'Envoyer un Message',
      'selectWhoYoudLikeToMessage': 'Sélectionnez qui vous souhaitez contacter pour obtenir du soutien:',
      'trustedContact': 'Contact de Confiance',
      'addFromPhonebook': 'Ajouter depuis le répertoire',
      'whatsappHopeCoreHubTeam': 'Équipe WhatsApp HopeCore Hub',
      'helloINeedHelpRegardingSafetyConcern': 'Bonjour, j\'ai besoin d\'aide concernant un problème de sécurité.',
      'addTrustedContact': 'Ajouter un Contact de Confiance',
      'contactName': 'Nom du Contact',
      'phoneNumber': 'Numéro de Téléphone',
      'pleaseEnterAValidPhoneNumber': 'Veuillez entrer un numéro de téléphone valide',
      'couldNotLaunchPhoneCall': 'Impossible de lancer l\'appel téléphonique vers [number]',
      'errorMakingPhoneCall': 'Erreur lors de l\'appel téléphonique: [error]',
      'couldNotLaunchSms': 'Impossible de lancer le SMS vers [number]',
      'errorSendingSms': 'Erreur lors de l\'envoi du SMS: [error]',
      'couldNotLaunchWhatsapp': 'Impossible de lancer WhatsApp. Veuillez vous assurer que WhatsApp est installé.',
      'errorSendingWhatsappMessage': 'Erreur lors de l\'envoi du message WhatsApp: [error]',
      'contactsPermissionRequired': 'L\'autorisation de contacts est requise pour sélectionner dans le répertoire.',
      'pleaseEnableContactsPermission': 'Veuillez activer l\'autorisation de contacts dans les paramètres de l\'application.',
      'errorAccessingContacts': 'Erreur lors de l\'accès aux contacts: [error]',
      'hiINeedToTalk': 'Salut, j\'ai besoin de parler. Pourriez-vous m\'appeler quand vous aurez un moment?',

      // Quick Access Section
      'quickAccess': 'Accès Rapide',
      'connectWithCommunity': 'Se connecter avec la communauté',
      'aiSupportCompanion': 'Compagnon de Soutien IA',
      'professionalSupport': 'Soutien Professionnel',
      'customizeYourExperience': 'Personnalisez votre expérience',

      // Mood Tracking Section
      'howCanWeSupportYouToday': 'Comment pouvons-nous vous soutenir aujourd\'hui?',
      'itsGreatToSeeYoureFeelingGood': 'C\'est formidable de voir que vous vous sentez bien! Souhaitez-vous partager vos expériences positives ou apprendre des moyens de maintenir cette humeur?',
      'sometimesWeAllFeelNeutral': 'Parfois, nous nous sentons tous un peu neutres. Souhaitez-vous parler de ce qui vous préoccupe ou explorer des moyens d\'améliorer votre humeur?',
      'imSorryYoureFeelingDown': 'Je suis désolé que vous vous sentiez mal. Rappelez-vous qu\'il est normal de ne pas aller bien, et en parler peut aider. Souhaitez-vous du soutien?',
      'iCanSeeYoureHavingDifficultTime': 'Je vois que vous traversez une période difficile. N\'oubliez pas que vous n\'êtes pas seul, et il existe des ressources disponibles pour vous aider.',
      'thankYouForSharingHowYoureFeeling': 'Merci de partager ce que vous ressentez. Souhaitez-vous en parler davantage?',
      'talkToMahoro': 'Parler à Mahoro',
      'joinForum': 'Rejoindre le Forum',

      // Emergency Contacts Footer
      'isangeOneStopCenterLabel': 'Isange One Stop Center:',
      'rwandaInvestigationBureauLabel': 'Bureau d\'Enquête du Rwanda (RIB):',
      'hopeCoreTeamLabel': 'Équipe HopeCore:',
      'helpIsAvailable247': 'L\'aide est disponible 24/7',

      // Daily Affirmation Section
      'dailyAffirmation': 'Affirmation Quotidienne',
      'dailyAffirmationQuote': 'Vous êtes plus fort que vous ne le pensez, plus courageux que vous ne le ressentez, et plus aimé que vous ne l\'imaginez.',

      // Guest Mode Messages
      'guestMode': 'Mode Invité',
      'youreCurrentlyUsingAppAsGuest': 'Vous utilisez actuellement l\'application en tant qu\'invité. Connectez-vous ou créez un compte pour accéder à toutes les fonctionnalités et sauvegarder vos progrès.',
      'loginRegister': 'Connexion / Inscription',
      'continueAsGuest': 'Continuer en tant qu\'Invité',
      'logInToAccessAllFeatures': 'Connectez-vous pour accéder à toutes les fonctionnalités',
      'refreshingLoginStatus': 'Actualisation du statut de connexion...',

      // Forum Screen
      'yourSafeSpaceToHeal': 'Votre Espace Sûr pour Guérir',
      'thisIsASafeModeratedSpace': 'C\'est un espace sûr et modéré. Toutes les publications sont anonymes et bienveillantes.',
      'postingAs': 'Publication en tant que',
      'youArePostingAsGuest': 'Vous publiez en tant qu\'invité. Connectez-vous pour suivre vos publications.',
      'title': 'Titre',
      'shareYourThoughts': 'Partagez vos pensées, expériences ou demandez du soutien...',
      'share': 'Partager',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'remove': 'Retirer',
      'flagReport': 'Signaler',
      'deletePost': 'Supprimer la Publication',
      'areYouSureYouWantToDelete': 'Êtes-vous sûr de vouloir supprimer cette publication? Cette action ne peut pas être annulée.',
      'postDeletedSuccessfully': 'Publication supprimée avec succès',
      'errorDeletingPost': 'Erreur lors de la suppression de la publication: [error]',
      'editPost': 'Modifier la Publication',
      'editYourMessage': 'Modifiez votre message...',
      'save': 'Enregistrer',
      'update': 'Mettre à jour',
      'postUpdatedSuccessfully': 'Publication mise à jour avec succès',
      'errorUpdatingPost': 'Erreur lors de la mise à jour de la publication: [error]',
      'replySentSuccessfully': 'Réponse envoyée avec succès',
      'errorSendingReply': 'Erreur lors de l\'envoi de la réponse: [error]',
      'typeAReply': 'Tapez une réponse...',
      'youHaveAlreadyLikedThisPost': 'Vous avez déjà aimé cette publication',
      'errorLikingPost': 'Erreur lors de l\'ajout d\'un like: [error]',
      'pleaseLogInToReply': 'Veuillez vous connecter pour répondre',
      'pleaseLogInToLikePosts': 'Veuillez vous connecter pour aimer les publications',
      'pleaseLogInToReportContent': 'Veuillez vous connecter pour signaler du contenu',
      'today': 'Aujourd\'hui',
      'yesterday': 'Hier',
      'monday': 'Lundi',
      'tuesday': 'Mardi',
      'wednesday': 'Mercredi',
      'thursday': 'Jeudi',
      'friday': 'Vendredi',
      'saturday': 'Samedi',
      'sunday': 'Dimanche',
      'jan': 'Jan',
      'feb': 'Fév',
      'mar': 'Mar',
      'apr': 'Avr',
      'may': 'Mai',
      'jun': 'Juin',
      'jul': 'Juil',
      'aug': 'Aoû',
      'sep': 'Sep',
      'oct': 'Oct',
      'nov': 'Nov',
      'dec': 'Déc',
      'areYouSureYouWantToLogout': 'Êtes-vous sûr de vouloir vous déconnecter?',
      'welcome': 'Bienvenue,',
      'youAreBrowsingAsGuest': 'Vous naviguez en tant qu\'invité',
      'loggedInAs': 'Connecté en tant que',
      'errorLoadingPostsUsingFallback': 'Erreur lors du chargement des publications. Utilisation du contenu de secours.',
      'errorCreatingPost': 'Erreur lors de la création de la publication: [error]',
      'errorLoadingPosts': 'Erreur lors du chargement des publications: [error]',
      'createAPost': 'Créer une Publication',
      'postingAsUsername': 'Publication en tant que [username]',

      // Mahoro AI Screen
      'aiSupportActive': 'Soutien IA Actif',
      'apiConnectionError': 'Erreur de Connexion API',
      'english': 'Anglais',
      'kinyarwanda': 'Kinyarwanda',
      'francais': 'Français',
      'swahili': 'Swahili',
      'murahoImMahoro': 'Bonjour! Je suis Mahoro, votre compagnon de soutien IA. Comment puis-je vous aider aujourd\'hui? Vous pouvez me parler en Kinyarwanda, Anglais, Swahili ou Français.',
      'apiKeyNotFound': 'Clé API introuvable. Veuillez contacter le support.',
      'apiKeyRemoved': 'Clé API supprimée. Mahoro demandera une nouvelle clé.',
      'pleaseEnterValidApiKey': 'Veuillez entrer une clé API valide',
      'invalidApiKeyFormat': 'Format de clé API invalide. Les clés Claude commencent par "sk-ant-"',
      'apiKeySaved': 'Clé API enregistrée. Mahoro est prêt à être utilisé.',
      'apiKeyUpdatedSuccessfully': 'Clé API mise à jour avec succès. Mahoro est prêt à être utilisé.',
      'claudeApiKey': 'Clé API Claude',
      'claudeApiKeyRequired': 'Clé API Claude Requise',
      'enterApiKey': 'Entrer la Clé API',
      'mahoroNeedsValidApiKey': 'Mahoro a besoin d\'une clé API Claude valide pour se connecter. Entrez une clé ci-dessous pour continuer.',
      'updateClaudeApiKeyDescription': 'Mettez à jour la clé API Claude pour Mahoro AI. La clé est stockée en toute sécurité sur cet appareil.',
      'enterClaudeApiKeyDescription': 'Entrez une clé API Claude pour activer Mahoro AI. La clé sera stockée en toute sécurité sur cet appareil.',
      'apiKeyLabel': 'Clé API',
      'updatingKeyWillAffectAllUsers': 'La mise à jour de la clé affectera tous les utilisateurs sur cet appareil.',
      'imHavingTroubleWithAuthentication': 'J\'ai des problèmes d\'authentification. Veuillez contacter le support.',
      'imHavingTroubleConnecting': 'J\'ai des difficultés à me connecter en ce moment. Veuillez réessayer plus tard.',
      'imSorryIEncounteredAnError': 'Je suis désolé, j\'ai rencontré une erreur. Veuillez réessayer.',
      'tooManyRequestsPleaseWait': 'Je reçois trop de demandes. Veuillez patienter un moment et réessayer.',
      'policeEmergency': 'Urgence Police',
      'errorLoadingPostsTitle': 'Impossible de Charger les Publications',
      'errorLoadingPostsRetry': 'Échec du chargement des publications. Veuillez vérifier votre connexion et réessayer.',
      'retry': 'Réessayer',
      'ifInImmediateDanger': 'Si vous êtes en danger immédiat, appelez les services d\'urgence',
      'ifInImmediateDangerCallEmergency': 'Si vous êtes en danger immédiat, veuillez appeler les services d\'urgence (112) ou utiliser le bouton SOS pour obtenir de l\'aide.',
      'report': 'Signaler',
      'thankYouForReportingContent': 'Merci d\'avoir signalé ce contenu. Nous l\'examinerons rapidement.',
      'your247SupportCompanion': 'Votre compagnon de soutien 24/7',

      // Muganga Therapy Screen
      'comingSoon': 'Bientôt Disponible',
      'mugangaTherapyCurrentlyInDevelopment': 'La Thérapie Muganga est actuellement en développement et sera bientôt lancée.',
      'weAreBuildingMostAffordable': 'Nous construisons le Soutien en Santé Mentale le plus abordable et adapté à la Génération Z au Rwanda.',
      'stayTunedForUpdates': 'Restez à l\'écoute pour les mises à jour!',
      'loadingSubscriptionData': 'Chargement des données d\'abonnement...',
      'errorLoadingSubscriptionData': 'Erreur lors du chargement des données d\'abonnement',
      'retry': 'Réessayer',

      // Settings Screen - Additional
      'reduceDataUsageForRemoteAreas': 'Réduire l\'utilisation des données pour les zones éloignées',
      'loadImagesOnlyWhenNeeded': 'Charger les images uniquement lorsque nécessaire',
      'cacheContentForOfflineAccess': 'Mettre en cache le contenu pour un accès hors ligne',
      'useDarkThemeThroughoutApp': 'Utiliser le thème sombre dans toute l\'application',
      'forumPosts': 'Publications du Forum',
      'newMessagesInForum': 'Nouveaux messages dans le forum',
      'forumRepliesLabel': 'Réponses du forum',
      'appUpdatesAndNews': 'Mises à jour et actualités de l\'application',
      'guestUser': 'Utilisateur Invité',
      'online': 'En Ligne',
      'pageComingSoon': 'page bientôt disponible',
      'pageIsNotYetImplemented': 'page pas encore implémentée',
      'dataPerformanceLabel': 'Performance des Données',
      'appearanceLabel': 'Apparence',
      'accessibilityLabel': 'Accessibilité',
      'notificationsLabel': 'Notifications',
      'emergencyContactsLabel': 'Contacts d\'Urgence',
      'selectFontFamilyLabel': 'Sélectionner la Police',
      'selectFontSizeLabel': 'Sélectionner la Taille de Police',
      'fontSizeFollowsDevice': 'La taille du texte suit les réglages d\'accessibilité de votre appareil.',
      'highContrastModeLabel': 'Mode Contraste Élevé',
      'reduceMotionLabel': 'Réduire les Animations',
      'textToSpeechLabel': 'Synthèse Vocale',
      'voiceToTextLabel': 'Reconnaissance Vocale',
      'darkModeLabel': 'Mode Sombre',
      'lowDataModeLabel': 'Mode Données Réduites',
      'imageLazyLoadingLabel': 'Chargement Différé des Images',
      'offlineModeLabel': 'Mode Hors Ligne',

      // Content Reporting Dialog
      'reportContent': 'Signaler le Contenu',
      'whyAreYouReportingThisContent': 'Pourquoi signalez-vous ce contenu?',
      'inappropriateContent': 'Contenu Inapproprié',
      'contentThatViolatesCommunityGuidelines': 'Contenu qui viole les directives de la communauté',
      'harmfulOrDangerous': 'Nocif ou Dangereux',
      'contentThatCouldCauseHarm': 'Contenu qui pourrait causer du tort aux utilisateurs',
      'spam': 'Spam',
      'unwantedOrRepetitiveContent': 'Contenu indésirable ou répétitif',
      'misinformation': 'Désinformation',
      'falseOrMisleadingInformation': 'Informations fausses ou trompeuses',
      'harassmentOrBullying': 'Harcèlement ou Intimidation',
      'contentThatTargetsOrBullies': 'Contenu qui cible ou intimide les utilisateurs',
      'other': 'Autre',
      'otherConcernsNotListed': 'Autres préoccupations non listées ci-dessus',
      'pleaseSpecify': 'Veuillez préciser',
      'additionalDetailsOptional': 'Détails supplémentaires (optionnel)',
      'provideAnyAdditionalContext': 'Fournissez tout contexte supplémentaire...',
      'submitReport': 'Soumettre le Rapport',
      'loading': 'Chargement...',
      'alreadyReported': 'Déjà Signalé',
      'youHaveAlreadyReportedThisContent': 'Vous avez déjà signalé ce contenu. Notre équipe de modération l\'examinera et prendra les mesures appropriées.',
      'ok': 'OK',
      'reportSubmittedSuccessfully': 'Rapport soumis avec succès. Merci de contribuer à la sécurité de notre communauté.',
      'failedToSubmitReport': 'Échec de la soumission du rapport. Veuillez réessayer.',
      'anErrorOccurred': 'Une erreur s\'est produite. Veuillez réessayer.',
      'pleaseSelectReasonForReporting': 'Veuillez sélectionner une raison pour signaler ce contenu.',
      'pleaseProvideCustomReason': 'Veuillez fournir une raison personnalisée.',
      'aiMessage': 'Message IA',
      'forumPost': 'Publication du Forum',
      'forumReply': 'Réponse du Forum',
      'otherContent': 'Autre Contenu',

      // Error & Success Messages
      'close': 'Fermer',
      'pickFromPhonebook': 'Sélectionner depuis le répertoire',
      'selectContact': 'Sélectionner un Contact',
      'mon': 'Lun',
      'tue': 'Mar',
      'wed': 'Mer',
      'thu': 'Jeu',
      'fri': 'Ven',
      'sat': 'Sam',
      'sun': 'Dim',
    },
    'Swahili': {
      // Transaction ID dialog
      'confirmYourPayment': 'Thibitisha Malipo Yako',
      'iUnderstand': 'Naelewa',
      'submit': 'Wasilisha',
      'pleaseEnterTheFinancialTransactionId':
          'Tafadhali ingiza Kitambulisho cha Shughuli ya Fedha kutoka ujumbe wako wa uthibitisho wa malipo wa MTN',
      'pleaseWaitForOurTeamToConfirmYourTransaction':
          'Tafadhali subiri timu yetu ithibitishe muamala wako. Hii kwa kawaida huchukua chini ya dakika 10 wakati wa saa za kazi.',
      'confirmAndSubmit': 'Thibitisha na Wasilisha',
      'transactionIdSubmittedSuccessfully':
          'Kitambulisho cha muamala kimewasilishwa kwa mafanikio. Timu yetu itathibitisha na kuamilisha akaunti yako hivi karibuni.',
      'pleaseEnterTransactionId':
          'Tafadhali ingiza Kitambulisho cha Muamala halali',

      // Settings
      'settings': 'Mipangilio',
      'darkMode': 'Hali ya Giza',
      'language': 'Lugha',
      'selectLanguage': 'Chagua Lugha',
      'cancel': 'Ghairi',
      'searchSettings': 'Tafuta Mipangilio',
      'selectFontFamily': 'Chagua Aina ya Fonti',
      'selectFontSize': 'Chagua Ukubwa wa Fonti',
      'languageAudio': 'Lugha na Sauti',
      'chooseLanguageDescription': 'Chagua lugha unayoipendelea',
      'chooseFontFamilyDescription':
          'Chagua aina ya maandishi inayosomeka vizuri',
      'fontSizeFollowsSystem':
          'Ukubwa wa maandishi unafuata mpangilio wa kifaa chako.',
      'database': 'Hifadhidata',
      'contentPolicyReporting': 'Sera ya Maudhui na Kuripoti',
      'adminControls': 'Vifaa vya Msimamizi',
      'lowDataMode': 'Hali ya Data Ndogo',
      'imageLazyLoading': 'Upakiaji wa Polepole wa Picha',
      'offlineMode': 'Hali ya Nje ya Mtandao',

      // Navigation
      'home': 'Nyumbani',
      'forum': 'Jukwaa',
      'mahoro': 'Mahoro',
      'muganga': 'Muganga',

      // Accessibility
      'accessibility': 'Ufikiaji',
      'fontFamily': 'Familia ya Fonti',
      'fontSize': 'Ukubwa wa Fonti',
      'highContrastMode': 'Hali ya Tofauti ya Juu',
      'reduceMotion': 'Punguza Mwendo',
      'textToSpeech': 'Maandishi hadi Usemi',
      'voiceToText': 'Sauti hadi Maandishi',

      // Appearance
      'appearance': 'Mwonekano',

      // Notifications
      'notifications': 'Arifa',
      'forumReplies': 'Majibu ya Jukwaa',
      'weeklyCheckIns': 'Ukaguzi wa Kila Wiki',
      'systemUpdates': 'Masasisho ya Mfumo',

      // Privacy & Security
      'privacySecurity': 'Faragha na Usalama',
      'emergencyContacts': 'Anwani za Dharura',
      'logout': 'Toka',
      'signIn': 'Ingia',
      'editProfile': 'Hariri Wasifu',

      // Forum
      'safeSpaceToShare': 'Nafasi salama ya kushiriki',
      'noPostsYet': 'Hakuna machapisho bado',
      'beTheFirstToStartConversation': 'Kuwa wa kwanza kuanza mazungumzo',
      'createPost': 'Unda Chapisho',
      'joinTheConvo': 'Jiunge na Mazungumzo',
      'search': 'Tafuta',
      'searchPosts': 'Tafuta machapisho...',
      'searchPostsLabel': 'Tafuta Machapisho',
      'searchLabel': 'Tafuta...',
      'likes': 'Penda',
      'replies': 'Majibu',
      'reply': 'Jibu',
      'anonymous': 'Bila jina',
      'postTitle': 'Kichwa cha Chapisho',
      'postContent': 'Maudhui ya Chapisho',
      'post': 'Chapisha',

      // Mahoro
      'yourSupportCompanion': 'Msaidizi wako wa kila wakati',
      'typeMessage': 'Andika ujumbe...',
      'send': 'Tuma',

      // Muganga
      'mugangaTherapy': 'Tiba ya Muganga',
      'professionalMentalHealthSupport': 'Msaada wa kitaalamu wa afya ya akili',
      'monthlySubscription': 'Usajili wa Kila Mwezi',
      '2000RWF': 'RWF 2,000',
      'unlimitedTherapySessionsWithCertifiedProfessionals':
          'Vikao vya tiba visivyo na kikomo na wataalamu wenye vyeti',
      'subscribeNow': 'Jiandikishe Sasa',
      'mtnMobileMoneyPayment': 'Malipo ya MTN Mobile Money',
      'payWithMtnMobileMoney': 'Ishyura na MTN Mobile Money',
      'dialTheFollowingUssdCodeOnYourMtnPhone':
          'Piga namba ifuatayo ya USSD kwenye simu yako ya MTN:',
      'ussdCode': '*182*1*1*0780332779*2000#',
      'afterPaymentYouWillReceive': 'Baada ya malipo, utapokea:',
      'immediateConfirmationMessage': 'Ujumbe wa uthibitisho wa haraka',
      'paymentReceiptFromOurTeam': 'Risiti ya malipo kutoka kwa timu yetu',
      'accessToTherapyBooking': 'Ufikiaji wa kuhifadhi tiba',
      'note': 'Kumbuka:',
      'paymentGoesDirectlyToOurTeamAt250780332779TheNumberIsRegisteredToAlineIRADUKUNDAOurChiefOperationsOfficerSheWillBeContactingYouAsSoonAsThePaymentIsReceivedForAccountActivation':
          'Malipo huenda moja kwa moja kwa timu yetu kwenye +250780332779. Namba imesajiliwa kwa Aline IRADUKUNDA, Afisa Mkuu wa Uendeshaji. Atakuwa akiwasiliana nawe mara tu malipo yatakapopokelewa kwa uanzishaji wa akaunti.',
      'iveMadeThePayment': 'Nimefanya Malipo',
      'payEasilyWithMtnMobileMoneyAndGetInstantAccessToProfessionalTherapy':
          'Ishyura byoroshye na MTN Mobile Money kandi ubone ubufasha bw\'inzobere ako kanya',
      'certifiedTherapists': 'Wataalamu Wenye Vyeti',
      'licensedMentalHealthProfessionals':
          'Wataalamu wa afya ya akili wenye leseni',
      'flexibleScheduling': 'Ratiba Rahisi',
      'bookSessionsAtYourConvenience': 'Weka vikao kwa urahisi wako',
      'oneOnOneSessions': 'Vikao vya Mtu kwa Mtu',
      'privateConfidentialTherapySessions':
          'Vikao vya tiba vya faragha na siri',

      // Home
      'welcomeBack': 'Karibu tena,',
      'yourSafeSpaceForHealing': 'Nafasi yako salama ya kupona',
      'emergencyHelp': 'SOS - Msaada wa Dharura',
      'getImmediateSupport': 'Pata msaada wa haraka',
      'emergencyCall': 'Simu ya Dharura',
      'wouldYouLikeToCallEmergencyServicesNow':
          'Ungependa kupiga simu kwa huduma za dharura sasa?',
      'callNow': 'Piga Simu Sasa',
      'exploreServices': 'Chunguza Huduma',
      'recentPosts': 'Machapisho ya Hivi Karibuni',
      'viewAll': 'Ona Yote',
      'quickActions': 'Vitendo vya Haraka',

      // Home - Mood tracking
      'howAreYouFeelingToday': 'Unajisikiaje leo?',
      'great': 'Vizuri Sana',
      'good': 'Vizuri',
      'okay': 'Kawaida',
      'sad': 'Huzuni',
      'bad': 'Vibaya',

      // Home - Resources
      'resources': 'Rasilimali',
      'selfCareTips': 'Vidokezo vya Kujitunza',
      'dailyWellnessPractices': 'Mazoezi ya kila siku ya afya',
      'safetyPlanning': 'Mpango wa Usalama',
      'personalSafetyResources': 'Rasilimali za usalama binafsi',
      'crisisSupport': 'Msaada wa Dharura',
      'helplineNumbers': 'Nambari za simu za msaada 24/7',
      'educationalContent': 'Maudhui ya Elimu',
      'learnAboutHealing': 'Jifunze kuhusu uponyaji',

      // App Name & Branding
      'hopeCoreHub': 'HopeCore Hub',
      'ignitingHope': 'Kuwasha Matumaini',

      // SOS/Emergency Section
      'sos': 'SOS',
      'youAreNotAlone': 'Huna Peke Yako',
      'everythingIsGoingToBeOkay': 'Kila kitu kitaenda sawa. 💜',
      'ifYoureInImmediateDanger': 'Ikiwa uko katika hatari ya haraka, tuko hapa kukusaidia kuwasiliana na msaada unaofaa.',
      'youAreBraveForReachingOut': 'Una ujasiri kwa kutufikia.',
      'howWouldYouLikeToGetHelp': 'Ungependa kupata msaada vipi?',
      'call': 'Piga Simu',
      'message': 'Ujumbe',
      'chooseEmergencyContact': 'Chagua Anwani ya Dharura',
      'selectWhoYoudLikeToCall': 'Chagua nani ungependa kumpigia simu kwa msaada wa haraka:',
      'isangeOneStopCenter': 'Isange One Stop Center',
      'genderBasedViolenceSupport': 'Msaada wa unyanyasaji wa kijinsia',
      'rwandaInvestigationBureau': 'Ofisi ya Uchunguzi ya Rwanda (RIB)',
      'criminalInvestigationsSafety': 'Uchunguzi wa jinai na usalama',
      'hopeCoreHubTeam': 'Timu ya HopeCore Hub',
      'wellHelpContactAuthorities': 'Tutakusaidia kuwasiliana na mamlaka',
      'back': 'Rudi',
      'makeAPhoneCall': 'Piga Simu',
      'sendATextMessage': 'Tuma SMS',
      'sendAMessage': 'Tuma Ujumbe',
      'selectWhoYoudLikeToMessage': 'Chagua nani ungependa kumtumia ujumbe kwa msaada:',
      'trustedContact': 'Anwani ya Kuaminika',
      'addFromPhonebook': 'Ongeza kutoka kwenye kitabu cha simu',
      'whatsappHopeCoreHubTeam': 'Timu ya WhatsApp HopeCore Hub',
      'helloINeedHelpRegardingSafetyConcern': 'Hujambo, nahitaji msaada kuhusu wasiwasi wa usalama.',
      'addTrustedContact': 'Ongeza Anwani ya Kuaminika',
      'contactName': 'Jina la Anwani',
      'phoneNumber': 'Nambari ya Simu',
      'pleaseEnterAValidPhoneNumber': 'Tafadhali ingiza nambari ya simu halali',
      'couldNotLaunchPhoneCall': 'Haiwezekani kuanzisha simu kwa [number]',
      'errorMakingPhoneCall': 'Hitilafu wakati wa kupiga simu: [error]',
      'couldNotLaunchSms': 'Haiwezekani kuanzisha SMS kwa [number]',
      'errorSendingSms': 'Hitilafu wakati wa kutuma SMS: [error]',
      'couldNotLaunchWhatsapp': 'Haiwezekani kuanzisha WhatsApp. Tafadhali hakikisha WhatsApp imesakinishwa.',
      'errorSendingWhatsappMessage': 'Hitilafu wakati wa kutuma ujumbe wa WhatsApp: [error]',
      'contactsPermissionRequired': 'Ruhusa ya anwani inahitajika ili kuchagua kutoka kwenye kitabu cha simu.',
      'pleaseEnableContactsPermission': 'Tafadhali wezesha ruhusa ya anwani katika mipangilio ya programu.',
      'errorAccessingContacts': 'Hitilafu wakati wa kufikia anwani: [error]',
      'hiINeedToTalk': 'Hujambo, nahitaji kuzungumza. Tafadhali unipigie simu unapopata nafasi?',

      // Quick Access Section
      'quickAccess': 'Ufikiaji wa Haraka',
      'connectWithCommunity': 'Wasiliana na jamii',
      'aiSupportCompanion': 'Msaidizi wa AI',
      'professionalSupport': 'Msaada wa Kitaalamu',
      'customizeYourExperience': 'Badilisha uzoefu wako',

      // Mood Tracking Section
      'howCanWeSupportYouToday': 'Tunaweza kukusaidia vipi leo?',
      'itsGreatToSeeYoureFeelingGood': 'Ni vizuri sana kuona unajisikia vizuri! Ungependa kushiriki uzoefu wako mzuri au kujifunza njia za kudumisha hali hii?',
      'sometimesWeAllFeelNeutral': 'Wakati mwingine sisi sote hujisikia kidogo tu. Ungependa kuzungumza kuhusu kile kinakukera au kuchunguza njia za kuboresha hali yako?',
      'imSorryYoureFeelingDown': 'Samahani kwa kujisikia vibaya. Kumbuka kuwa si shida kujisikia vibaya, na kuzungumza kuhusu hilo kunaweza kusaidia. Ungependa msaada?',
      'iCanSeeYoureHavingDifficultTime': 'Naona una wakati mgumu. Tafadhali kumbuka kuwa huna peke yako, na kuna rasilimali zinazopatikana kukusaidia.',
      'thankYouForSharingHowYoureFeeling': 'Asante kwa kushiriki jinsi unavyojisikia. Ungependa kuzungumza zaidi kuhusu hilo?',
      'talkToMahoro': 'Ongea na Mahoro',
      'joinForum': 'Jiunge na Jukwaa',

      // Emergency Contacts Footer
      'isangeOneStopCenterLabel': 'Isange One Stop Center:',
      'rwandaInvestigationBureauLabel': 'Ofisi ya Uchunguzi ya Rwanda (RIB):',
      'hopeCoreTeamLabel': 'Timu ya HopeCore:',
      'helpIsAvailable247': 'Msaada unapatikana 24/7',

      // Daily Affirmation Section
      'dailyAffirmation': 'Uthibitisho wa Kila Siku',
      'dailyAffirmationQuote': 'Uko hodari zaidi kuliko unavyojua, ujasiri zaidi kuliko unavyojisikia, na unapendwa zaidi kuliko unavyofikiria.',

      // Guest Mode Messages
      'guestMode': 'Hali ya Mgeni',
      'youreCurrentlyUsingAppAsGuest': 'Unatumia programu kama mgeni. Ingia au uunde akaunti ili kufikia vipengele vyote na kuokoa maendeleo yako.',
      'loginRegister': 'Ingia / Jisajili',
      'continueAsGuest': 'Endelea kama Mgeni',
      'logInToAccessAllFeatures': 'Ingia ili kufikia vipengele vyote',
      'refreshingLoginStatus': 'Inasasisha hali ya kuingia...',

      // Forum Screen
      'yourSafeSpaceToHeal': 'Nafasi Yako Salama ya Kupona',
      'thisIsASafeModeratedSpace': 'Hii ni nafasi salama na inayoongozwa. Machapisho yote ni ya bila jina na yenye msaada.',
      'postingAs': 'Kuchapisha kama',
      'youArePostingAsGuest': 'Unachapisha kama mgeni. Ingia ili kufuatilia machapisho yako.',
      'title': 'Kichwa',
      'shareYourThoughts': 'Shiriki mawazo yako, uzoefu, au uliza msaada...',
      'share': 'Shiriki',
      'edit': 'Hariri',
      'delete': 'Futa',
      'remove': 'Ondoa',
      'flagReport': 'Ripoti',
      'deletePost': 'Futa Chapisho',
      'areYouSureYouWantToDelete': 'Je, una uhakika unataka kufuta chapisho hili? Kitendo hiki hakiwezi kutenduliwa.',
      'postDeletedSuccessfully': 'Chapisho limefutwa kwa mafanikio',
      'errorDeletingPost': 'Hitilafu katika kufuta chapisho: [error]',
      'editPost': 'Hariri Chapisho',
      'editYourMessage': 'Hariri ujumbe wako...',
      'save': 'Hifadhi',
      'update': 'Sasisha',
      'postUpdatedSuccessfully': 'Chapisho limebadilishwa kwa mafanikio',
      'errorUpdatingPost': 'Hitilafu katika kusasisha chapisho: [error]',
      'replySentSuccessfully': 'Jibu limetumwa kwa mafanikio',
      'errorSendingReply': 'Hitilafu katika kutuma jibu: [error]',
      'typeAReply': 'Andika jibu...',
      'youHaveAlreadyLikedThisPost': 'Tayari umependa chapisho hili',
      'errorLikingPost': 'Hitilafu katika kupenda chapisho: [error]',
      'pleaseLogInToReply': 'Tafadhali ingia ili kujibu',
      'pleaseLogInToLikePosts': 'Tafadhali ingia ili kupenda machapisho',
      'pleaseLogInToReportContent': 'Tafadhali ingia ili kuripoti maudhui',
      'today': 'Leo',
      'yesterday': 'Jana',
      'monday': 'Jumatatu',
      'tuesday': 'Jumanne',
      'wednesday': 'Jumatano',
      'thursday': 'Alhamisi',
      'friday': 'Ijumaa',
      'saturday': 'Jumamosi',
      'sunday': 'Jumapili',
      'jan': 'Jan',
      'feb': 'Feb',
      'mar': 'Mar',
      'apr': 'Apr',
      'may': 'Mei',
      'jun': 'Jun',
      'jul': 'Jul',
      'aug': 'Ago',
      'sep': 'Sep',
      'oct': 'Okt',
      'nov': 'Nov',
      'dec': 'Des',
      'areYouSureYouWantToLogout': 'Je, una uhakika unataka kutoka?',
      'welcome': 'Karibu,',
      'youAreBrowsingAsGuest': 'Unavinjari kama mgeni',
      'loggedInAs': 'Umeingia kama',
      'errorLoadingPostsUsingFallback': 'Hitilafu katika kupakia machapisho. Kutumia maudhui ya dharura.',
      'errorCreatingPost': 'Hitilafu katika kuunda chapisho: [error]',
      'errorLoadingPosts': 'Hitilafu katika kupakia machapisho: [error]',
      'createAPost': 'Unda Chapisho',
      'postingAsUsername': 'Kuchapisha kama [username]',

      // Mahoro AI Screen
      'aiSupportActive': 'Msaada wa AI Uko Hai',
      'apiConnectionError': 'Hitilafu ya Muunganisho wa API',
      'english': 'Kiingereza',
      'kinyarwanda': 'Kinyarwanda',
      'francais': 'Kifaransa',
      'swahili': 'Kiswahili',
      'murahoImMahoro': 'Hujambo! Mimi ni Mahoro, msaidizi wako wa AI. Ninaweza kukusaidia vipi leo? Unaweza kuzungumza nami kwa Kinyarwanda, Kiingereza, Kiswahili, au Kifaransa.',
      'apiKeyNotFound': 'Ufunguo wa API haujapatikana. Tafadhali wasiliana na msaada.',
      'apiKeyRemoved': 'Ufunguo wa API umeondolewa. Mahoro atauliza ufunguo mpya.',
      'pleaseEnterValidApiKey': 'Tafadhali ingiza ufunguo wa API halali',
      'invalidApiKeyFormat': 'Muundo wa ufunguo wa API si sahihi. Funguo za Claude huanza na "sk-ant-"',
      'apiKeySaved': 'Ufunguo wa API umehifadhiwa. Mahoro tayari kutumika.',
      'apiKeyUpdatedSuccessfully': 'Ufunguo wa API umeonyeshwa kwa mafanikio. Mahoro tayari kutumika.',
      'claudeApiKey': 'Ufunguo wa API wa Claude',
      'claudeApiKeyRequired': 'Ufunguo wa API wa Claude Unahitajika',
      'enterApiKey': 'Ingiza Ufunguo wa API',
      'mahoroNeedsValidApiKey': 'Mahoro anahitaji ufunguo wa API wa Claude halali ili kuunganisha. Ingiza ufunguo hapa chini ili kuendelea.',
      'updateClaudeApiKeyDescription': 'Sasisha ufunguo wa API wa Claude kwa Mahoro AI. Ufunguo umehifadhiwa kwa usalama kwenye kifaa hiki.',
      'enterClaudeApiKeyDescription': 'Ingiza ufunguo wa API wa Claude ili kuwezesha Mahoro AI. Ufunguo utahifadhiwa kwa usalama kwenye kifaa hiki.',
      'apiKeyLabel': 'Ufunguo wa API',
      'updatingKeyWillAffectAllUsers': 'Kusasisha ufunguo kutaathiri watumiaji wote kwenye kifaa hiki.',
      'imHavingTroubleWithAuthentication': 'Nina shida na uthibitishaji. Tafadhali wasiliana na msaada.',
      'imHavingTroubleConnecting': 'Nina shida kuunganisha sasa hivi. Tafadhali jaribu tena baadaye.',
      'imSorryIEncounteredAnError': 'Samahani, nimekutana na hitilafu. Tafadhali jaribu tena.',
      'tooManyRequestsPleaseWait': 'Napokea maombi mengi sana. Tafadhali subiri kidogo na ujaribu tena.',
      'policeEmergency': 'Dharura ya Polisi',
      'errorLoadingPostsTitle': 'Haiwezekani Kupakia Machapisho',
      'errorLoadingPostsRetry': 'Imeshindwa kupakia machapisho. Tafadhali angalia muunganisho wako na ujaribu tena.',
      'retry': 'Jaribu Tena',
      'ifInImmediateDanger': 'Ikiwa uko katika hatari ya haraka, piga huduma za dharura',
      'ifInImmediateDangerCallEmergency': 'Ikiwa uko katika hatari ya haraka, tafadhali piga huduma za dharura (112) au tumia kitufe cha SOS kwa msaada.',
      'report': 'Ripoti',
      'thankYouForReportingContent': 'Asante kwa kuripoti maudhui haya. Tutayachunguza haraka.',
      'your247SupportCompanion': 'Msaidizi wako wa kila wakati 24/7',

      // Muganga Therapy Screen
      'comingSoon': 'Inakuja Hivi Karibuni',
      'mugangaTherapyCurrentlyInDevelopment': 'Tiba ya Muganga iko katika maendeleo na itazinduliwa hivi karibuni.',
      'weAreBuildingMostAffordable': 'Tunajenga Msaada wa Afya ya Akili unaofaa zaidi na unaofaa kwa GenZ nchini Rwanda.',
      'stayTunedForUpdates': 'Endelea kufuatilia kwa masasisho!',
      'loadingSubscriptionData': 'Inapakia data za usajili...',
      'errorLoadingSubscriptionData': 'Hitilafu katika kupakia data za usajili',
      'retry': 'Jaribu Tena',

      // Settings Screen - Additional
      'reduceDataUsageForRemoteAreas': 'Punguza matumizi ya data kwa maeneo ya mbali',
      'loadImagesOnlyWhenNeeded': 'Pakia picha tu zinapohitajika',
      'cacheContentForOfflineAccess': 'Hifadhi maudhui kwa ufikiaji nje ya mtandao',
      'useDarkThemeThroughoutApp': 'Tumia mandhari ya giza katika programu yote',
      'forumPosts': 'Machapisho ya Jukwaa',
      'newMessagesInForum': 'Ujumbe mpya katika jukwaa',
      'forumRepliesLabel': 'Majibu ya jukwaa',
      'appUpdatesAndNews': 'Masasisho na habari za programu',
      'guestUser': 'Mtumiaji Mgeni',
      'online': 'Mtandaoni',
      'pageComingSoon': 'ukurasa unakuja hivi karibuni',
      'pageIsNotYetImplemented': 'ukurasa haujatekelezwa bado',
      'dataPerformanceLabel': 'Utendakazi wa Data',
      'appearanceLabel': 'Mwonekano',
      'accessibilityLabel': 'Ufikiaji',
      'notificationsLabel': 'Arifa',
      'emergencyContactsLabel': 'Anwani za Dharura',
      'selectFontFamilyLabel': 'Chagua Aina ya Fonti',
      'selectFontSizeLabel': 'Chagua Ukubwa wa Fonti',
      'fontSizeFollowsDevice': 'Ukubwa wa maandishi unafuata mpangilio wa kifaa chako.',
      'highContrastModeLabel': 'Hali ya Tofauti ya Juu',
      'reduceMotionLabel': 'Punguza Mwendo',
      'textToSpeechLabel': 'Maandishi hadi Usemi',
      'voiceToTextLabel': 'Sauti hadi Maandishi',
      'darkModeLabel': 'Hali ya Giza',
      'lowDataModeLabel': 'Hali ya Data Ndogo',
      'imageLazyLoadingLabel': 'Upakiaji wa Polepole wa Picha',
      'offlineModeLabel': 'Hali ya Nje ya Mtandao',

      // Content Reporting Dialog
      'reportContent': 'Ripoti Maudhui',
      'whyAreYouReportingThisContent': 'Kwa nini unaripoti maudhui haya?',
      'inappropriateContent': 'Maudhui Yasiyofaa',
      'contentThatViolatesCommunityGuidelines': 'Maudhui yanayokiuka miongozo ya jamii',
      'harmfulOrDangerous': 'Yenye Madhara au Hatari',
      'contentThatCouldCauseHarm': 'Maudhui ambayo yanaweza kusababisha madhara kwa watumiaji',
      'spam': 'Barua Taka',
      'unwantedOrRepetitiveContent': 'Maudhui yasiyotakiwa au yanayorudiwa',
      'misinformation': 'Taarifa za Uongo',
      'falseOrMisleadingInformation': 'Taarifa za uwongo au za kupotosha',
      'harassmentOrBullying': 'Unyanyasaji au Udhalilishaji',
      'contentThatTargetsOrBullies': 'Maudhui yanayolenga au kudhalilisha watumiaji',
      'other': 'Nyingine',
      'otherConcernsNotListed': 'Wasiwasi wengine ambao hayajaorodheshwa hapo juu',
      'pleaseSpecify': 'Tafadhali eleza',
      'additionalDetailsOptional': 'Maelezo ya ziada (si lazima)',
      'provideAnyAdditionalContext': 'Toa muktadha wowote wa ziada...',
      'submitReport': 'Wasilisha Ripoti',
      'loading': 'Inapakia...',
      'alreadyReported': 'Tayari Imeripotiwa',
      'youHaveAlreadyReportedThisContent': 'Tayari umeripoti maudhui haya. Timu yetu ya uangalizi itayachunguza na kuchukua hatua zinazofaa.',
      'ok': 'Sawa',
      'reportSubmittedSuccessfully': 'Ripoti imewasilishwa kwa mafanikio. Asante kwa kusaidia kuweka jamii yetu salama.',
      'failedToSubmitReport': 'Kushindwa kuwasilisha ripoti. Tafadhali jaribu tena.',
      'anErrorOccurred': 'Hitilafu imetokea. Tafadhali jaribu tena.',
      'pleaseSelectReasonForReporting': 'Tafadhali chagua sababu ya kuripoti maudhui haya.',
      'pleaseProvideCustomReason': 'Tafadhali toa sababu maalum.',
      'aiMessage': 'Ujumbe wa AI',
      'forumPost': 'Chapisho la Jukwaa',
      'forumReply': 'Jibu la Jukwaa',
      'otherContent': 'Maudhui Mengine',

      // Error & Success Messages
      'close': 'Funga',
      'pickFromPhonebook': 'Chagua kutoka kwenye kitabu cha simu',
      'selectContact': 'Chagua Anwani',
      'mon': 'Jtn',
      'tue': 'Jnn',
      'wed': 'Jtn',
      'thu': 'Alh',
      'fri': 'Ijm',
      'sat': 'Jms',
      'sun': 'Jpl',
    },
    'Kinyarwanda': {
      // Transaction ID dialog
      'confirmYourPayment': 'Emeza Ubwishyu Bwawe',
      'iUnderstand': 'Ndabyumva',
      'submit': 'Ohereza',
      'pleaseEnterTheFinancialTransactionId':
          'Nyamuneka andika Nomero y\'Ubwishyu (Transaction ID) ivuye mu butumwa bwo kwemeza ubwishyu bwa MTN',
      'pleaseWaitForOurTeamToConfirmYourTransaction':
          'Nyamuneka tegereza ikipe yacu kugira ngo yemeze ubwishyu bwawe. Ibi bisanzwe bifata munsi y\'iminota 10 mu masaha y\'akazi.',
      'confirmAndSubmit': 'Emeza & Ohereza',
      'transactionIdSubmittedSuccessfully':
          'Nomero y\'Ubwishyu yoherejwe neza. Ikipe yacu izabyemeza kandi ikore konti yawe vuba.',
      'pleaseEnterTransactionId':
          'Nyamuneka andika Nomero y\'Ubwishyu ifite agaciro',

      // Settings
      'settings': 'Igena',
      'darkMode': 'Ibara y\'Umukara',
      'language': 'Ururimi',
      'selectLanguage': 'Hitamo Ururimi',
      'cancel': 'Kureka',
      'searchSettings': 'Shakisha Igenamiterere',
      'selectFontFamily': 'Hitamo Ubwoko bw\'Imyandikire',
      'selectFontSize': 'Hitamo Ingano y\'Imyandikire',
      'languageAudio': 'Ururimi & Ijwi',
      'chooseLanguageDescription': 'Hitamo ururimi wumva neza',
      'chooseFontFamilyDescription':
          'Hitamo imisusire y\'inyuguti yoroshye gusoma',
      'fontSizeFollowsSystem':
          'Ingano y\'inyuguti ikurikira igenamiterere rya telefone yawe.',
      'database': 'Ububiko bw\'Itangazamakuru',
      'contentPolicyReporting': 'Politiki y\'Ibikubiyemo n\'Itangazwa',
      'adminControls': 'Igenzura ry\'Abayobozi',
      'lowDataMode': 'Uburyo bwa Data Nkeya',
      'imageLazyLoading': 'Gutangiza Amashusho Buhoro',
      'offlineMode': 'Uburyo bwo Hanze y\'Umurongo',

      // Navigation
      'home': 'Ahabanza',
      'forum': 'Urubuga',
      'mahoro': 'Mahoro',
      'muganga': 'Muganga',

      // Accessibility
      'accessibility': 'Ubushobozi bwo Kugera',
      'fontFamily': 'Umuryango w\'Imyandikire',
      'fontSize': 'Ingano y\'Imyandikire',
      'highContrastMode': 'Uburyo bw\'Itandukaniro Rikomeye',
      'reduceMotion': 'Kugabanya Imyitozo',
      'textToSpeech': 'Umwandiko ujya mu Mvugo',
      'voiceToText': 'Ijwi rijya mu Mwandiko',

      // Appearance
      'appearance': 'Imiterere',

      // Notifications
      'notifications': 'Imenyesha',
      'forumReplies': 'Ibisubizo by\'Ihuriro',
      'weeklyCheckIns': 'Isuzuma rya buri Cyumweru',
      'systemUpdates': 'Ivugururwa rya Sisitemu',

      // Privacy & Security
      'privacySecurity': 'Ubuzima Bwite n\'Umutekano',
      'emergencyContacts': 'Aho Wahamagara mu Bihe Bikomeye',
      'logout': 'Gusohoka',
      'signIn': 'Kwinjira',
      'editProfile': 'Guhindura Umwirondoro',

      // Forum
      'safeSpaceToShare': 'Your Safe Space to Heal',
      'noPostsYet': 'Nta post zirashyirwamo',
      'beTheFirstToStartConversation': 'Ba uwa mbere mu kwinikiza ikiganiro ',
      'createPost': 'Andika Nawe',
      'joinTheConvo': 'Join The Convo',
      'search': 'Shakisha',
      'searchPosts': 'Shakisha posts',
      'searchPostsLabel': 'Shakisha posts',
      'searchLabel': 'Shakisha…',
      'likes': 'Bikunda',
      'replies': 'Ibisubizo',
      'reply': 'Subiza',
      'anonymous': 'Ntamwirondoro',
      'postTitle': 'Umutwe w\'Inyandiko',
      'postContent': 'Ibikubiye mu Nyandiko',
      'post': 'Ohereza',

      // Mahoro
      'yourSupportCompanion': 'Umufasha wawe w\'igihe cyose',
      'typeMessage': 'Andika ubutumwa...',
      'send': 'Ohereza',

      // Muganga
      'mugangaTherapy': 'Ubuvuzi bwa Muganga',
      'professionalMentalHealthSupport':
          'Ubufasha bw\'inzobere mu buzima bwo mu mutwe',
      'monthlySubscription': 'Kwiyandikisha kwa Buri Kwezi',
      '2000RWF': 'RWF 2,000',
      'unlimitedTherapySessionsWithCertifiedProfessionals':
          'Amasaha y\'ubuvuzi adafite umupaka n\'impuguke zemewe',
      'subscribeNow': 'Iyandikishe Nonaha',
      'mtnMobileMoneyPayment': 'Kwishyura na MTN Mobile Money',
      'payWithMtnMobileMoney': 'Ishyura na MTN Mobile Money',
      'dialTheFollowingUssdCodeOnYourMtnPhone':
          'Kanda kode ya USSD ikurikira kuri telefoni yawe ya MTN:',
      'ussdCode': '*182*1*1*0780332779*2000#',
      'afterPaymentYouWillReceive': 'Nyuma yo kwishyura, uzakira:',
      'immediateConfirmationMessage': 'Ubutumwa bwo kwemeza ako kanya',
      'paymentReceiptFromOurTeam':
          'Inyemezabuguzi yo kwishyura ivuye mu ikipe yacu',
      'accessToTherapyBooking': 'Uburenganzira bwo kwiyandikisha ku buvuzi',
      'note': 'Icyitonderwa:',
      'paymentGoesDirectlyToOurTeamAt250780332779TheNumberIsRegisteredToAlineIRADUKUNDAOurChiefOperationsOfficerSheWillBeContactingYouAsSoonAsThePaymentIsReceivedForAccountActivation':
          'Amafaranga ajya ku ikipe yacu kuri +250780332779. Nimero yanditswe kuri Aline IRADUKUNDA, Umuyobozi w\'Ibikorwa. Azakuvugisha vuba nyuma y\'uko amafaranga yakiriwe kugira ngo akore konti yawe.',
      'iveMadeThePayment': 'Nakoze Ubwishyu',
      'payEasilyWithMtnMobileMoneyAndGetInstantAccessToProfessionalTherapy':
          'Ishyura byoroshye na MTN Mobile Money kandi ubone ubufasha bw\'inzobere ako kanya',
      'certifiedTherapists': 'Abavuzi Bemewe',
      'licensedMentalHealthProfessionals':
          'Inzobere mu buzima bwo mu mutwe zifite impushya',
      'flexibleScheduling': 'Gahunda Yoroshye',
      'bookSessionsAtYourConvenience': 'Iyandikishe ku masaha bikugoye',
      'oneOnOneSessions': 'Amasaha y\'Umuntu ku Muntu',
      'privateConfidentialTherapySessions':
          'Amasaha y\'ubuvuzi yihariye kandi afite ibanga',

      // Home
      'welcomeBack': 'Murakaza neza,',
      'yourSafeSpaceForHealing': 'Umwanya wawe utekanye wo gukira',
      'emergencyHelp': 'SOS - Ubufasha Bwihutirwa',
      'getImmediateSupport': 'Bona ubufasha bwihuse',
      'emergencyCall': 'Guhamagara Byihutirwa',
      'wouldYouLikeToCallEmergencyServicesNow':
          'Urifuza guhamagara serivisi z\'ubutabazi ubu?',
      'callNow': 'Hamagara Ubu',
      'exploreServices': 'Reba Serivisi',
      'recentPosts': 'Inyandiko za Vuba',
      'viewAll': 'Reba Byose',
      'quickActions': 'Ibikorwa Byihuse',

      // Home - Mood tracking
      'howAreYouFeelingToday': 'Mbwira, urumva umeze ute?',
      'great': 'Neza cyane',
      'good': 'Neza',
      'okay': 'Ntaribi',
      'sad': 'Ndababaye',
      'bad': 'Nabi',

      // Home - Resources
      'resources': 'Ibyagufasha',
      'selfCareTips': 'Kwiyitaho',
      'dailyWellnessPractices': 'Uko wakwiyitaho buri munsi',
      'safetyPlanning': 'Gutekana',
      'personalSafetyResources': 'Gira uruhare ku mutekano wawe',
      'crisisSupport': 'Ubufasha mu makuba',
      'helplineNumbers': 'Nimero z\'ubutabazi 24/7',
      'educationalContent': 'Ubumenyi Rusange',
      'learnAboutHealing': 'Menya ku gukira ihungabana',

      // App Name & Branding
      'hopeCoreHub': 'HopeCore Hub',
      'ignitingHope': 'Igniting Hope',

      // SOS/Emergency Section
      'sos': 'SOS',
      'youAreNotAlone': 'Humura, Nturi Wenyine',
      'everythingIsGoingToBeOkay': 'Byose biraza kumera neza 💜',
      'ifYoureInImmediateDanger': 'Niba ubona/wumva uri mu byago, humura turagufasha!',
      'youAreBraveForReachingOut': 'Wagize ubutwari kutugana.',
      'howWouldYouLikeToGetHelp': 'Ni ubuhe buryo bukoroheye?',
      'call': 'Hamagara',
      'message': 'Andikira',
      'chooseEmergencyContact': 'Urifuza Guhamagara He?',
      'selectWhoYoudLikeToCall': 'Hitamo abo uhamagara bajyanye n\'ubufasha ukeneye.',
      'isangeOneStopCenter': 'Isange One Stop Center',
      'genderBasedViolenceSupport': 'Ubuvuzi, ubujyanama, ubutabera, n\' Icumbi k\'uwahohotewe.',
      'rwandaInvestigationBureau': 'Ikigo cy\'Igihugu gishinzwe Ubugenzacyaha (RIB)',
      'criminalInvestigationsSafety': 'Ubugenzacyaha, Ubutabazi bwihuse',
      'hopeCoreHubTeam': 'Ingabo HopeCore',
      'wellHelpContactAuthorities': 'Turaguhamagarira inzego zibishinzwe',
      'back': 'Subira Inyuma',
      'makeAPhoneCall': 'Hamagara',
      'sendATextMessage': 'Ohereza Ubutumwa',
      'sendAMessage': 'Ohereza Ubutumwa',
      'selectWhoYoudLikeToMessage': 'Hitamo uwo wandikira ngo agufashe',
      'trustedContact': 'Abantu Bawe Wizeye',
      'addFromPhonebook': 'Hitamo mubo muziranye',
      'whatsappHopeCoreHubTeam': 'Twandikire Kuri Whatsapp',
      'helloINeedHelpRegardingSafetyConcern': 'Muraho, nkeneye ubufasha bwihutirwa.',
      'addTrustedContact': 'Hitamo mubo muziranye',
      'contactName': 'Izina ry\'Umuntu',
      'phoneNumber': 'Nimero ya Telephone',
      'pleaseEnterAValidPhoneNumber': 'Subiramo, wandike nimero neza',
      'couldNotLaunchPhoneCall': 'Ntibishoboka guhamagara [number]',
      'errorMakingPhoneCall': 'Ikosa mu guhamagara: [error]',
      'couldNotLaunchSms': 'Ntibishoboka kohereza SMS kuri [number]',
      'errorSendingSms': 'Ikosa mu kohereza SMS: [error]',
      'couldNotLaunchWhatsapp': 'Ntibishoboka gufungura WhatsApp. Nyamuneka menya ko WhatsApp yashyizweho.',
      'errorSendingWhatsappMessage': 'Ikosa mu kohereza ubutumwa bwa WhatsApp: [error]',
      'contactsPermissionRequired': 'Uburenganzira bwo gusura abantu baziranye burakenewe kugira ngo hitamwe mu buziranye.',
      'pleaseEnableContactsPermission': 'Nyamuneka fungura uburenganzira bwo gusura abantu baziranye mu miterere y\'apurikasiyo.',
      'errorAccessingContacts': 'Ikosa mu gusura abantu baziranye: [error]',
      'hiINeedToTalk': 'Uraho neza, nkeneye kukuvugisha byihutirwa, umpamagare nubona akanya.',

      // Quick Access Section
      'quickAccess': 'Iriburiro',
      'connectWithCommunity': 'Ganira n\'urungano',
      'aiSupportCompanion': 'Umufasha-koranabuhanga',
      'professionalSupport': 'Ubujyanama mu isanamitima n\'ihungabana',
      'customizeYourExperience': 'Gena uko ushaka apurikasiyo',

      // Mood Tracking Section
      'howCanWeSupportYouToday': 'Nkufashe nte uyu munsi?',
      'itsGreatToSeeYoureFeelingGood': 'Birashimishije kumva ko umeze neza! Urifuza gusangiza abandi ibi byishimo cg kumenya uko wahorana aka kanyamuneza?',
      'sometimesWeAllFeelNeutral': 'Si wowe gusa, hari igihe nanjye mba numva ntazi. Niba ntacyo bigutwaye, mbwira ibikuremereye, cg twiganirire uko wamera neza.',
      'imSorryYoureFeelingDown': 'Nyabusa ihangane kandi komera. Buriya kugira uwo ubwira ntako bisa. Wumva wifuza uwo wabwira?',
      'iCanSeeYoureHavingDifficultTime': 'Ndabyumva bambe uraremerewe. Ariko kandi nyabusa, nturi wenyine. Uru rubuga urufiteho umuryango n\'ubufasha bw\'ingeri nyinshi.',
      'thankYouForSharingHowYoureFeeling': 'Urakoze kumbwira uko umeze. Tubiganireho byimbitse?',
      'talkToMahoro': 'Ganira na Mahoro',
      'joinForum': 'Ganira n\'Urungano',

      // Emergency Contacts Footer
      'isangeOneStopCenterLabel': 'Isange One Stop Center:',
      'rwandaInvestigationBureauLabel': 'Ikigo cy\'Igihugu gishinzwe Ubugenzacyaha (RIB):',
      'hopeCoreTeamLabel': 'HopeCore Team:',
      'helpIsAvailable247': 'Ubutabazi n\'ubufasha birahari 24/7',

      // Daily Affirmation Section
      'dailyAffirmation': 'Ijambo ry\'Umunsi',
      'dailyAffirmationQuote': 'You are stronger than you know, braver than you feel, and more loved than you imagine.',

      // Guest Mode Messages
      'guestMode': 'Konte y\'Umushyitsi',
      'youreCurrentlyUsingAppAsGuest': 'Urimo gukoresha HopeCore Hub nk\'umushyitsi. Injiramo na konti kugira ngo ukoreshe serivisi zose.',
      'loginRegister': 'Injira na konti / Iyandikishe',
      'continueAsGuest': 'Komeza nk\'Umushyitsi',
      'logInToAccessAllFeatures': 'Injiramo na konti kugira ngo ukoreshe serivisi zose',
      'refreshingLoginStatus': 'Tegereza gato, igenzura…',

      // Forum Screen
      'yourSafeSpaceToHeal': 'Twiganirire, Nkuteze Yombi.',
      'thisIsASafeModeratedSpace': 'Uru rubuga ruratekanye, rurizewe, nawe ucira undi urubanza. Ibiganiro byose bigamije kubakana no kugirana inama. Izina ryawe ntirigaragarira abandi.',
      'postingAs': 'Urapostinga nka',
      'youArePostingAsGuest': 'Urapostinga nk\'umushyitsi. Injiramo na konti kugira ngo ukomeze ikiganiro n\'abandi.',
      'title': 'Umutwe',
      'shareYourThoughts': 'Vuga ikikuri ku mutima, cg ugishe inama…',
      'share': 'Sangiza',
      'edit': 'Hindura',
      'delete': 'Siba',
      'remove': 'Kuramo',
      'flagReport': 'Flag/Report',
      'deletePost': 'Siba Post',
      'areYouSureYouWantToDelete': 'Nibyo koko ushaka gusiba iyi post? Ibisibwe ntibigaruka.',
      'postDeletedSuccessfully': ' Post yawe yasibwe.',
      'errorDeletingPost': 'Ntibikunze gusiba post: [error]',
      'editPost': 'Hindura Post',
      'editYourMessage': 'Hindura post yawe',
      'save': 'Emeza',
      'update': 'Ongera',
      'postUpdatedSuccessfully': 'Post yawe yahinduwe neza',
      'errorUpdatingPost': 'Ntibikuze guhindura post: [error]',
      'replySentSuccessfully': 'Igisubizo cyawe cyoherejwe neza',
      'errorSendingReply': 'Ntibikunze kohereza igisubizo: [error]',
      'typeAReply': 'Andika usubiza…',
      'youHaveAlreadyLikedThisPost': 'Iyi post already wayikunze',
      'errorLikingPost': 'Ntibikunze gukunda iyi post [error]',
      'pleaseLogInToReply': 'Banza winjire kuri konti kugira ngo usubize',
      'pleaseLogInToLikePosts': 'Injira kuri konti ubone gukunda posts',
      'pleaseLogInToReportContent': 'Injira kugira ngo urepportinge post',
      'createAPost': 'Andika Nawe',
      'postingAsUsername': 'Urapostinga nka [username]',
      'today': 'Uyu munsi',
      'yesterday': 'Ejo',
      'monday': 'Kuwa Mbere',
      'tuesday': 'Kuwa Kabiri',
      'wednesday': 'Kuwa Gatatu',
      'thursday': 'Kuwa Kane',
      'friday': 'Kuwa Gatanu',
      'saturday': 'Kuwa Gatandatu',
      'sunday': 'Ku Cyumweru',
      'jan': 'Mutarama',
      'feb': 'Gashyantare',
      'mar': 'Werurwe',
      'apr': 'Mata',
      'may': 'Gicurasi',
      'jun': 'Kamena',
      'jul': 'Nyakanga',
      'aug': 'Kanama',
      'sep': 'Nzeri',
      'oct': 'Ukwakira',
      'nov': 'Ugushyingo',
      'dec': 'Ukuboza',
      'areYouSureYouWantToLogout': 'Nibyo, urashaka gusohoka muri konti?',
      'welcome': 'Ikaze, murisanga',
      'youAreBrowsingAsGuest': 'Uri gukoresha nk\'umushyitsi',
      'loggedInAs': 'Winjiyemo nka',
      'errorLoadingPostsUsingFallback': 'Ntibikunze kuzana posts. Harakoresha iyagenwe.',
      'errorCreatingPost': 'Ntibikuze gupostinga: [error]',
      'errorLoadingPosts': 'Ntibikunze kuzana posts: [error]',
      'errorLoadingPostsTitle': 'Ntibishoboka Kuzana Posts',
      'errorLoadingPostsRetry': 'Ntibikunze kuzana posts. Nyamuneka gerageza kandi ugerageze nanone.',
      'retry': 'Gerageza Nanone',
      'ifInImmediateDanger': 'Niba uri mu kaga, hamagara serivisi z\'ingoboka',
      'ifInImmediateDangerCallEmergency': 'Niba uri mu kaga, nyamuneka hamagara serivisi z\'ingoboka (112) cg ukoreshe buto ya SOS kugira ngo ugire ubufasha.',
      'tooManyRequestsPleaseWait': 'Nakiriye ibyo usaba byinshi. Nyamuneka tegereza gato hanyuma ugerageze nanone.',
      'policeEmergency': 'Police Emergency',

      // Mahoro AI Screen
      'aiSupportActive': 'AI Support Active',
      'apiConnectionError': 'API Connection Error',
      'english': 'English',
      'kinyarwanda': 'Ikinyarwanda',
      'francais': 'French',
      'swahili': 'Swahili',
      'murahoImMahoro': 'Uraho neza bambe, nitwa Mahoro, ndi inshuti yawe-koranahubanga wakwizera, ndi hano ngo tuganire. Nagufasha nte uyu munsi? Ntakibazo, mbwira mu Kinyarwanda, Icyongereza, Igiswahili, cyangwa Igifaransa, ndagusubiza.',
      'apiKeyNotFound': 'API key not found. Please contact support.',
      'apiKeyRemoved': 'API key yakuweho. Mahoro azasaba key nshya.',
      'pleaseEnterValidApiKey': 'Nyamuneka andika API key ifite agaciro',
      'invalidApiKeyFormat': 'Imiterere y\'API key ntiyemewe. API keys za Claude zatangira na "sk-ant-"',
      'apiKeySaved': 'API key yabitswe. Mahoro iritegura gukoreshwa.',
      'apiKeyUpdatedSuccessfully': 'API key yongeyeho neza. Mahoro iritegura gukoreshwa.',
      'claudeApiKey': 'API Key ya Claude',
      'claudeApiKeyRequired': 'API Key ya Claude Ikenewe',
      'enterApiKey': 'Andika API Key',
      'mahoroNeedsValidApiKey': 'Mahoro ikeneye API key ya Claude ifite agaciro kugira ngo ihuze. Andika key hepfo kugira ngo ukomeze.',
      'updateClaudeApiKeyDescription': 'Ongera API key ya Claude kuri Mahoro AI. Key yabitswe mu buryo bwiteguye kuri iyi mudasobwa.',
      'enterClaudeApiKeyDescription': 'Andika API key ya Claude kugira ngo Mahoro AI ikore. Key izabitswe mu buryo bwiteguye kuri iyi mudasobwa.',
      'apiKeyLabel': 'API Key',
      'updatingKeyWillAffectAllUsers': 'Guhindura key bizagira ingaruka ku bakoresha bose kuri iyi mudasobwa.',
      'imHavingTroubleWithAuthentication': 'I\'m having trouble with authentication. Please contact support.',
      'imHavingTroubleConnecting': 'I\'m having trouble connecting right now. Please try again later.',
      'imSorryIEncounteredAnError': 'I\'m sorry, I encountered an error. Please try again.',
      'report': 'Reportinga',
      'thankYouForReportingContent': 'Urakoze ku reportinga iyi message. Turabigenzura bwangu.',
      'your247SupportCompanion': 'Ndi inshuti yawe ihari 24/7',

      // Muganga Therapy Screen
      'comingSoon': 'Iraza Vuba',
      'mugangaTherapyCurrentlyInDevelopment': 'Muganga Therapy iracyatunganywa, iratangira gukoreshwa vuba.',
      'weAreBuildingMostAffordable': 'Turimo kububakira ubufasha muby\'ubuzima bwo mu mutwe, isanamitima n\'ihungabana, buhendutse, bukoresha ikoranabuhanga kandi bunogeye n\'aba GenZ.',
      'stayTunedForUpdates': 'Ube hafi, tuzakumenyesha!',
      'loadingSubscriptionData': 'Loading subscription data...',
      'errorLoadingSubscriptionData': 'Error loading subscription data',
      'retry': 'Ongera ugerageze',

      // Settings Screen - Additional
      'reduceDataUsageForRemoteAreas': 'Gabanya data ahari rezo nkeya',
      'loadImagesOnlyWhenNeeded': 'Load images only when needed',
      'cacheContentForOfflineAccess': 'Cache content for offline access',
      'useDarkThemeThroughoutApp': 'Ijimisha apurikasiyo',
      'forumPosts': 'Forum Posts',
      'newMessagesInForum': 'New messages in the forum',
      'forumRepliesLabel': 'Forum replies',
      'appUpdatesAndNews': 'App updates and news',
      'guestUser': 'Guest User',
      'online': 'Online',
      'pageComingSoon': 'page coming soon',
      'pageIsNotYetImplemented': 'page is not yet implemented',
      'dataPerformanceLabel': 'Uko ukoresha data zawe',
      'appearanceLabel': 'Imigaragarire',
      'accessibilityLabel': '',
      'notificationsLabel': '',
      'emergencyContactsLabel': 'Inimero z\'Ubutabazi',
      'selectFontFamilyLabel': 'Hitamo Font',
      'selectFontSizeLabel': 'Hitamo Ingano y\'Amagabo',
      'fontSizeFollowsDevice': 'Ingano y\'amagambo ikurikiza igenamiterere rya telephone yawe.',
      'highContrastModeLabel': 'Bonesha cyane',
      'reduceMotionLabel': 'Gabanya Motions',
      'textToSpeechLabel': 'Text-to-Speech',
      'voiceToTextLabel': 'Voice-to-Text',
      'darkModeLabel': 'Ijimisha',
      'lowDataModeLabel': 'Gukoresha data nkeya',
      'imageLazyLoadingLabel': 'Gabanya Motions',
      'offlineModeLabel': 'Koresha nta interineti',

      // Content Reporting Dialog
      'reportContent': 'Report Content',
      'whyAreYouReportingThisContent': 'Why are you reporting this content?',
      'inappropriateContent': 'Inappropriate Content',
      'contentThatViolatesCommunityGuidelines': 'Content that violates community guidelines',
      'harmfulOrDangerous': 'Harmful or Dangerous',
      'contentThatCouldCauseHarm': 'Content that could cause harm to users',
      'spam': 'Spam',
      'unwantedOrRepetitiveContent': 'Unwanted or repetitive content',
      'misinformation': 'Misinformation',
      'falseOrMisleadingInformation': 'False or misleading information',
      'harassmentOrBullying': 'Harassment or Bullying',
      'contentThatTargetsOrBullies': 'Content that targets or bullies users',
      'other': 'Other',
      'otherConcernsNotListed': 'Other concerns not listed above',
      'pleaseSpecify': 'Please specify',
      'additionalDetailsOptional': 'Additional details (optional)',
      'provideAnyAdditionalContext': 'Provide any additional context...',
      'submitReport': 'Submit Report',
      'loading': 'Loading...',
      'alreadyReported': 'Already Reported',
      'youHaveAlreadyReportedThisContent': 'You have already reported this content. Our moderation team will review it and take appropriate action.',
      'ok': 'OK',
      'reportSubmittedSuccessfully': 'Report submitted successfully. Thank you for helping keep our community safe.',
      'failedToSubmitReport': 'Failed to submit report. Please try again.',
      'anErrorOccurred': 'An error occurred. Please try again.',
      'pleaseSelectReasonForReporting': 'Please select a reason for reporting this content.',
      'pleaseProvideCustomReason': 'Please provide a custom reason.',
      'aiMessage': 'AI Message',
      'forumPost': 'Forum Post',
      'forumReply': 'Forum Reply',
      'otherContent': 'Other Content',

      // Error & Success Messages
      'close': 'Close',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
    },
  };

  String translate(String key) {
    // Return translation if available, otherwise return the key itself
    return _localizedValues[locale]?[key] ??
        _localizedValues['English']?[key] ??
        key;
  }
}
