default_platform(:ios)

platform :ios do
  desc "Build IPA file"
  lane :build_ipa do
    setup_ci if ENV['CI']
    
    match(
      type: "appstore",
      readonly: is_ci,
      app_identifier: "com.ingabohopecore.hopecorehub"
    )
    
    gym(
      scheme: "Runner",
      export_method: "app-store",
      output_name: "Runner.ipa"
    )
  end
end 